      - name: Notify to Telegram After Deploy
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          FULL_MESSAGE="${{ github.event.head_commit.message }}"
          TITLE=$(echo "$FULL_MESSAGE" | head -n1)
          DESCRIPTION=$(echo "$FULL_MESSAGE" | tail -n +2)

          if [ -z "$DESCRIPTION" ]; then
            DESCRIPTION="(Tidak ada deskripsi)"
          fi

          MESSAGE=$(cat <<EOF
✅ *Berhasil Deploy ke Server Development*

Repo: \`${{ github.repository }}\`
Contributor: \`${{ github.actor }}\`
Judul Commit: \`${TITLE}\`
Deskripsi:

\`\`\`
${DESCRIPTION}
\`\`\`

[Lihat Commit](${{ github.event.head_commit.url }})
EOF
)

          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d text="$MESSAGE" \
            -d parse_mode=Markdown
