name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Code to cPanel
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            git pull origin main &&
            exit"

      - name: Notify to Telegram After Deploy
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          FULL_MESSAGE="${{ github.event.head_commit.message }}"
          TITLE=$(echo "$FULL_MESSAGE" | head -n1)
          DESCRIPTION=$(echo "$FULL_MESSAGE" | tail -n +2)

          if [ -z "$DESCRIPTION" ]; then
            DESCRIPTION="(Tidak ada deskripsi)"
          fi

          MESSAGE=$(cat <<EOF
✅ *Berhasil Deploy ke Server Development*

*Repo:* \`${{ github.repository }}\`
*Contributor:* \`${{ github.actor }}\`
*Judul Commit:* \`${TITLE}\`
*Deskripsi:*
\`\`\`
${DESCRIPTION}
\`\`\`
[Lihat Commit](${{ github.event.head_commit.url }})
EOF
)

          response=$(curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d "text=$MESSAGE" \
            -d parse_mode=Markdown)

          echo "Telegram Response: $response"

      - name: Notify Deployment Completion to GitHub Issue
        run: |
          echo "Starting to create issue comment..."
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.TOKENS }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                  "body": "**✅ Berhasil Deploy ke Development Server**:\n- **Branch**: main\n- **Last Commit**: '${{ github.sha }}'\n- **Link**: [Lihat](http://dev.kopmensa.com)\n\nSilahkan lihat di server."
                }' \
            https://api.github.com/repos/${{ github.repository }}/issues/1/comments)

          echo "API response from comment creation: $response"

          echo "Starting to assign assignee..."
          assign_response=$(curl -X PATCH \
            -H "Authorization: token ${{ secrets.TOKENS }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                  "assignees": ["alfianharisusatya"]
                }' \
            https://api.github.com/repos/${{ github.repository }}/issues/1)

          echo "API response from assignee assignment: $assign_response"
