name: Deploy and Notify

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="*Notifikasi commit dari \`${{ github.repository }}\`*\n\n- Contributor: \`${{ github.actor }}\`\n- Pesan:\n\`\`\`\n${{ github.event.head_commit.message }}\n\`\`\`\n- [Lihat Commit](${{ github.event.head_commit.url }})"

          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2

  deploy:
    runs-on: ubuntu-latest
    needs: notify   # deploy akan jalan setelah notify selesai
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Connection
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Code to cPanel
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            git pull origin main &&
            exit"

      - name: Notify Deployment Completion to GitHub
        run: |
          echo "Starting to create issue comment..."
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.TOKENS }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                  "body": "**Berhasil Deploy ke Development Server **:\n- **Branch**: main\n- **Last Commit**: '${{ github.sha }}'\n- **Link**: [Lihat](http://dev.kopmensa.com)\n\n **Silahkan lihat di server.**" 
                }' \
            https://api.github.com/repos/${{ github.repository }}/issues/1/comments)
          
          echo "API response from comment creation: $response"

          echo "Starting to assign assignee..."
          assign_response=$(curl -X PATCH \
            -H "Authorization: token ${{ secrets.TOKENS }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                  "assignees": ["alfianharisusatya"]
                }' \
            https://api.github.com/repos/${{ github.repository }}/issues/1)

          echo "API response from assignee assignment: $assign_response"
